#!/bin/bash

errors=0

run_tests() {
  testname=$1
  cmdgen=$2
  cmddef=$3
  cmdinf=$4

  for sz in 1 5 10 50 100 500 1000 5000 10000 50000 100000 500000 1000000 ; do
    printf "= %8s ~%10d:" "$testname" $sz

    for i in `seq 1 10` ; do 
      $cmdgen "./test.tmp" $(($sz + ($RANDOM%1000)))
      $cmddef < "./test.tmp" | $cmdinf | diff -q "./test.tmp" -

      if [ $? -eq 0 ] ; then
        echo -en " [$i: OK ]"
        rm -f "./test.tmp"
      else
        echo -en " [$i:BLAD]"
        mv "./test.tmp" "./bad-$testname-$sz-$i.txt"
        let errors+=1
      fi
    done
    echo
  done
}

run_tests "bin+file" "./Zfilegen" "./Zdef" "./Zinf"
run_tests "txt+file" "./Ztextgen" "./Zdef" "./Zinf"
run_tests "txt+line" "./Ztextgen" "./Zdef" "./Zgetline"

if [ $errors -eq 0 ] ; then
  echo "= -------- ~ ---------: OK" 
else
  echo "Bledow: $errors"
fi

